### ISSUE TITLE
Create The select quantity on the product screen

### ISSUE THREAD

**Issue by yfabio** [yfabio/techshop#9]
The product Screen needs a select in which the user will be able to select how many items they are going to buy. The quantity of options need to be the same as count in stock of each product.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added a select element to allow users to choose the quantity of items they want to buy, based on the product's count in stock. The select is placed above the 'Add to Cart' button and is disabled when the product is out of stock.

You can review changes in this commit: https://github.com/mnmnk43434/yfabio-techshop-9/commit/d87cbd5e8027ab2a6626c956ceb80d1eda6183cb.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by yfabio** [comment]
Created the select element where the user selects how many items they are going to purchase. The select has the same amount as count in stock.
